version: '3.7'

services:
  postgres:
    image: "postgres"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Mult-e@2
      - POSTGRES_DB=projeto
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

